name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Remove unnecessary directories
      run: |
        if [ -d "/usr/share/dotnet" ]; then
          sudo rm -rf /usr/share/dotnet
        fi
        if [ -d "$AGENT_TOOLSDIRECTORY" ]; then
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        fi
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
